#!/bin/bash

PYTHON=python
UPLOAD_PY="$HOME/myrepo/scripts/codereview/upload.py"
CR_SERVER="codereview.10gen.com"
EMAIL=bob.grabar@10gen.com

"$PYTHON" "$UPLOAD_PY" \
\--server "$CR_SERVER" \
\--email "$EMAIL" \
\--jira_user "bgrabar" \
"$@"
