#!/bin/bash

set -e

jiraUsername=bgrabar
emailAddress=bob.grabar@mongodb.com

# get the commit message
msg=`git log -1 --oneline | cut -d' ' -f2-`
hash=`git rev-parse HEAD`
hash=$hash~..$hash

if [[ $# -eq 0 ]]; then
   # just last commit
   python2 ~/myrepo/scripts/codereview/upload.py -y \
       --jira_user $jiraUsername --email $emailAddress -m "$msg" $hash
else
   # issue given
   issue=$1

   python2 ~/myrepo/scripts/codereview/upload.py -y \
       --jira_user $jiraUsername --email $emailAddress -m "$msg" -i $issue $hash
fi
