#!/bin/bash

jiraUsername=bgrabar
emailAddress=bob.grabar@mongodb.com
codereviewdir='/Users/bob/myrepo/scripts/codereview'

# get the commit message
msg=`git log -1 --oneline | cut -d' ' -f2-`
hash=`git rev-parse HEAD`
hash=`git rev-parse HEAD~`..${hash}
# Tells how many commits to send

if [[ $# -eq 0 ]]; then
# just last commit
python "$codereviewdir/upload.py" -m "$msg" --rev $hash --jira_user $jiraUsername
else
# issue given

if [ $1 == "--help" ]; then
 echo "First: issue; Second: hash; Third: message."
 exit 0
fi

issue=$1
hash=$2
msg=$3
python "$codereviewdir/upload.py" -m "$msg" -i $issue --rev $hash  --jira_user $jiraUsername
fi

#eof