#!/bin/bash

set -e

jiraUsername=bgrabar
emailAddress=bob.grabar@10gen.com

# get the commit message
msg=`git log -1 --oneline | cut -d' ' -f2-`
hash=`git rev-parse de5e56fcc8ad897bee9a332fe172352b551e3e93..HEAD`

if [[ $# -eq 0 ]]; then
   # just last commit
   python ~/myrepo/mongodb/tools/upload.py -y -s codereview.10gen.com \
       --jira_user $jiraUsername \
       --email $emailAddress -m "$msg" $hash
else
   # issue given
   issue=$1

   python ~/myrepo/mongodb/tools/upload.py -y -s codereview.10gen.com \
       --email $emailAddress -m "$msg" -i $issue $hash
fi
